### PR TITLE
Fix 'BEGIN_REPLACE' - used in tool_communication

### PR DESCRIPTION
**Pull request by rxjia**
Fix the position of 'BEGIN_REPLACE' - used in tool_communication

### CODE REVIEW

**Comment by rxjia** [comment]
The {{BEGIN_REPLACE}} before "# HEADER_BEGIN" will not be executed by "externalcontrol-1.0.5.urcap".
Therefore, the "tool_voltage" setting is invalid when use_tool_communication=true.

**Review by fmauch — APPROVED** [review]
Seems good to me, thanks!

**Comment by fmauch** [comment]
@Mergifyio  backport master

**Comment by fmauch** [comment]
@Mergifyio copy master

**Pull request merged**
