### PR TITLE
Added tests for the control interface classes

### PR DESCRIPTION
**Pull request by urmahp**

### CODE REVIEW

**Comment by fmauch** [comment]
Let's rebase this once #107 got merged.

**Comment by fmauch** [comment]
Rebased onto current master so all CI step should succeed.

**Review by fmauch — APPROVED** [review]
Looks good to me. Moving the setup into the fixtures is a debatable feature, so I'll approve this, but will only merge this after discussing that topic.

**Comment by urmahp** [comment]
> Looks good to me. Moving the setup into the fixtures is a debatable feature, so I'll approve this, but will only merge this after discussing that topic.

I think it would be a good idea to make the setup part of the fixture, since it is identical for all the tests, so I will have a look at that.

**Comment by fmauch** [comment]
Squashed to re-trigger code-cov report.

**Comment by fmauch** [comment]
Just for clarity: This is currently being held back as @urmahp wanted to move code to the test fixture. Once this is done, this should be ready to merge.

**Pull request merged**
