### PR TITLE
Boost staging

### PR DESCRIPTION
**Pull request by fmauch**
Merge the latest changes made on the master branch to the boost branch. The purpose of the boost-staging branch is that we have a merged state that we can manually edit and run the CI against.

@urmahp This should include the changes from your log_handler

### CODE REVIEW

**Comment by fmauch** [comment]
I'll put this to draft, so we can include #42 into this.

**Comment by urmahp** [comment]
> @urmahp This should include the changes from your log_handler

Nice thanks for your help @fmauch. 

Looks like the changes to CMakeList.txt from [commit](https://github.com/UniversalRobots/Universal_Robots_Client_Library/commit/77f0eac35362d06c81e521f6500ad76d8c08005e#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a) didn't get included in this PR. The file is not part of the files changed page in this PR.

**Comment by fmauch** [comment]
> Looks like the changes to CMakeList.txt from [commit](https://github.com/UniversalRobots/Universal_Robots_Client_Library/commit/77f0eac35362d06c81e521f6500ad76d8c08005e#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a) didn't get included in this PR. The file is not part of the files changed page in this PR.

Yes, I missed that.

**Comment by fmauch** [comment]
@t-schnell @stefanscherzinger @urmahp please test, as this will become a new release soon.

**Comment by urmahp** [comment]
It looks good to me, I have tested that it works with the Isaac driver and also the ROS driver.

**Comment by urrsk** [comment]
@stefanscherzinger when do you have time to review this PR

**Review by stefanscherzinger — APPROVED** [review]
Sorry guys, I didn't want to hold this back so long. I formally approve this. Maybe @t-schnell should have yet another brief look?

**Comment by fmauch** [comment]
I'll merge later today.

**Pull request merged**
