### PR TITLE
add reverse_ip

### PR DESCRIPTION
**Pull request by JS00000**
This PR is copied from [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/268), which can help the socket in the UR's Teach Pendant know the host IP address when this library is running in the Docker container (especially in Docker for Windows).

### CODE REVIEW

**Comment by fmauch** [comment]
@JS00000 just letting you know: I haven't forgotten this, it#s just a lot of other things currently going on in the library. I'll address this once #65 is merged.

**Comment by fmauch** [comment]
@JS00000 could you please rebase this ontop of the current master? Or alternatively allow edits from maintainers for this PR, then I can push the changes I've done locally (resolving the conflicts) directly to your branch.

**Comment by JS00000** [comment]
> @JS00000 could you please rebase this ontop of the current master? Or alternatively allow edits from maintainers for this PR, then I can push the changes I've done locally (resolving the conflicts) directly to your branch.

I have done that. And I realize that I need clone [ur_msgs](https://github.com/ros-industrial/ur_msgs) and fetch the new calibration_devel of [universal_robot](https://github.com/fmauch/universal_robot) to build project successfully. There are a lot of changes.

**Review by fmauch — APPROVED** [review]
lgtm

**Pull request merged**
